# Generated by Django 3.0.2 on 2020-01-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200110_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='parentList',
            new_name='listwrapper',
        ),
    ]
